from app.openai_config import build_openai_client

from .schemas import DecomposedQuery


class QueryDecomposer:
    """
    Breaks a natural language query into structured entities used for
    intent routing, source selection, and cache key construction.
    """

    INTENT_SOURCES = {
        "traffic":      ["drivebc"],
        "weather":      ["weathercan"],
        "emergency":    ["911_dispatch", "public_safety"],
        "obstruction":  ["drivebc", "public_safety"],
        "construction": ["drivebc"],
        "transit":      ["translink"],
        "general":      ["drivebc", "translink", "weathercan", "911_dispatch"],
    }

    def __init__(self, model: str = "gpt-4o"):
        self.client = build_openai_client()
        self.model = model
        self.system_prompt = (
            "You are a query decomposer for Situate Vancouver, a real-time city monitoring system. "
            "Extract structured entities from a natural language query about Vancouver's city conditions.\n\n"
            "Intent must be one of: traffic | weather | emergency | obstruction | construction | transit | general\n"
            "time_reference must be one of: current | forecast | historical\n"
            "location: canonical Vancouver name (e.g. 'Burrard Bridge', 'Waterfront Station'). Empty string if none.\n"
            "location_key: snake_case version for cache keys (e.g. 'burrard_bridge'). Empty string if none.\n"
            "sub_intents: specific aspects e.g. ['congestion', 'accident'] for traffic.\n"
            "entities: all named places, transit lines, and landmarks mentioned.\n\n"
            "Normalize location names: 'Burrard Street Bridge' → 'Burrard Bridge'."
        )

    def decompose(self, query: str) -> DecomposedQuery:
        """
        Decompose a natural language query into structured entities.

        Args:
            query: Raw user question, e.g. "Why is traffic so bad on Burrard Bridge?"

        Returns:
            DecomposedQuery with cache_key and retrieval_targets attached.
        """
        response = self.client.beta.chat.completions.parse(
            model=self.model,
            response_format=DecomposedQuery,
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": query},
            ],
        )
        result = response.choices[0].message.parsed

        # Attach derived fields not generated by the LLM
        parts = [result.intent]
        if result.location_key:
            parts.append(result.location_key)
        parts.append(result.time_reference)

        result.cache_key = ":".join(parts)
        result.retrieval_targets = self.INTENT_SOURCES.get(
            result.intent, self.INTENT_SOURCES["general"]
        )
        return result
