from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Decomposer
# ---------------------------------------------------------------------------

class DecomposedQuery(BaseModel):
    intent: str = Field(
        description="Primary intent: traffic | weather | emergency | obstruction | construction | transit | general"
    )
    location: str = Field(
        description="Canonical Vancouver location name. Empty string if none."
    )
    location_key: str = Field(
        description="snake_case normalized location for cache keys. Empty string if none."
    )
    time_reference: str = Field(
        description="current | forecast | historical"
    )
    sub_intents: list[str] = Field(
        description="More specific aspects of the query, e.g. ['congestion', 'accident']"
    )
    entities: list[str] = Field(
        description="All named entities extracted: streets, stations, lines, landmarks"
    )
    # Attached by decomposer after LLM call — not generated by the model
    cache_key: str = ""
    retrieval_targets: list[str] = []


# ---------------------------------------------------------------------------
# Retriever
# ---------------------------------------------------------------------------

class RetrievedContext(BaseModel):
    location_context: str = Field(
        description="What this place is and why it matters for city flow"
    )
    known_patterns: list[str] = Field(
        description="Recurring issues or patterns at this location"
    )
    related_locations: list[str] = Field(
        description="Nearby streets, stations, or areas that may be affected"
    )
    transit_lines_affected: list[str] = Field(
        description="Specific TransLink routes or lines impacted"
    )
    contributing_factors: list[str] = Field(
        description="Likely causes given the intent and context"
    )
    data_sources_checked: list[str] = Field(
        description="Which feeds are most relevant for this query"
    )
    confidence: float = Field(
        description="0.0-1.0 confidence in retrieved context quality"
    )
    cache_hit: bool = False


# ---------------------------------------------------------------------------
# Watcher
# ---------------------------------------------------------------------------

class Coordinates(BaseModel):
    lat: float
    lng: float


class DetectedIncident(BaseModel):
    event_detected: bool
    incident_type: str = Field(
        description="traffic_incident | transit_delay | weather_disruption | emergency | public_safety"
    )
    location: str = Field(description="Specific Vancouver location")
    coordinates: Coordinates = Field(description="lat/lng of the incident. Vancouver is ~49.28N, 123.12W")
    severity: str = Field(description="low | medium | high | critical")
    summary: str = Field(description="One-sentence description for map pin tooltip")
    raw_details: str
    affects_transit: bool
    timestamp: str = Field(description="ISO 8601 UTC timestamp")


# ---------------------------------------------------------------------------
# Reasoner
# ---------------------------------------------------------------------------

class ReasonerOutput(BaseModel):
    answer: str = Field(
        description="Direct conversational answer to the user's question (2-4 sentences)"
    )
    cause: str = Field(description="Root cause of the incident or situation")
    impact: str = Field(description="Who and what is affected")
    reasoning_steps: list[str] = Field(description="Chain-of-thought steps used to reach the answer")
    recommended_actions: list[str] = Field(description="Practical advice for commuters or city operators")
    estimated_duration: str = Field(description="How long this situation is likely to last")
    severity: str = Field(description="low | medium | high | critical")
    related_alerts: list[str] = Field(description="Other locations or lines commuters should know about")
    coordinates: Coordinates = Field(
        description=(
            "Best lat/lng for the primary location in this response. "
            "Use coordinates from the incident if available, otherwise estimate precisely "
            "for the named Vancouver location. Vancouver is ~49.28°N, 123.12°W. "
            "Always provide a specific value — never leave as 0,0."
        )
    )
    confidence: float = Field(description="0.0-1.0 confidence in this reasoning")


# ---------------------------------------------------------------------------
# Final orchestrator response — what the API returns to the frontend
# ---------------------------------------------------------------------------

class QueryResponse(BaseModel):
    original_query: str = Field(description="The raw question asked by the user")
    query_type: str = Field(
        description="Classified intent: traffic | weather | emergency | obstruction | construction | transit | general"
    )
    verdict: str = Field(description="Plain-English answer to the user's question")
    severity: str = Field(description="low | medium | high | critical")
    location: str = Field(description="The Vancouver location this response is about")
    coordinates: Coordinates = Field(description="lat/lng for the map pin — always present")
    cause: str
    impact: str
    recommended_actions: list[str]
    estimated_duration: str
    related_alerts: list[str]
    cache_hit: bool = Field(description="Whether this response was served from cache")
    confidence: float
