"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent

# Load repo-root .env (monorepo single source of env vars).
load_dotenv(REPO_ROOT / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-change-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,backend',
    ).split(',')
    if h.strip()
]

# Dev-only: accept any Host header (helps some Cloudflare Tunnel / proxy setups).
# Never use with DEBUG=false in production.
if DEBUG and os.environ.get('DJANGO_ALLOW_ALL_HOSTS', '').lower() in (
    '1',
    'true',
    'yes',
):
    ALLOWED_HOSTS = ['*']

_csrf_trusted = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in _csrf_trusted.split(',') if o.strip()
]

# Trust X-Forwarded-* from Cloudflare Tunnel / reverse proxy (HTTPS at the edge).
if os.environ.get('DJANGO_USE_X_FORWARDED_HEADERS', '').lower() in (
    '1',
    'true',
    'yes',
):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'apps.core.apps.CoreConfig',
    'apps.vancouver_opendata.apps.VancouverOpenDataConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- API / CORS (dev defaults; override via env in production) ---

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

_cors_origins = os.environ.get(
    'DJANGO_CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

AI_SERVICE_URL = os.environ.get('AI_SERVICE_URL', 'http://127.0.0.1:8001')
AI_QUERY_TIMEOUT_SECONDS = float(
    os.environ.get('AI_QUERY_TIMEOUT_SECONDS', '120'),
)

# Aggregate /api/health: set HEALTH_CHECK_AI=false when FastAPI is not running locally.
HEALTH_CHECK_AI = os.environ.get('HEALTH_CHECK_AI', 'true').lower() in (
    '1',
    'true',
    'yes',
)

# --- Vancouver Open Data (CKAN) ---
_van_base = os.environ.get(
    'VANCOUVER_OPENDATA_BASE_URL',
    'https://opendata.vancouver.ca',
).rstrip('/')
VANCOUVER_OPENDATA_BASE_URL = _van_base
VANCOUVER_OPENDATA_API_KEY = os.environ.get('VANCOUVER_OPENDATA_API_KEY', '').strip()
VANCOUVER_OPENDATA_TIMEOUT_SECONDS = float(
    os.environ.get('VANCOUVER_OPENDATA_TIMEOUT_SECONDS', '10'),
)
VANCOUVER_OPENDATA_ENFORCE_HOST_ALLOWLIST = os.environ.get(
    'VANCOUVER_OPENDATA_ENFORCE_HOST_ALLOWLIST',
    'true',
).lower() in ('1', 'true', 'yes')

# Optional: GET this URL (aggregate /api/health JSON) and copy checks.vancouver_opendata.
# For local dev pointing at production (e.g. ageforty). Do not set to this deployment's own URL.
HEALTH_VANCOUVER_OPENDATA_STATUS_URL = os.environ.get(
    'HEALTH_VANCOUVER_OPENDATA_STATUS_URL',
    '',
).strip()
