# Generated by Django 6.0.3 on 2026-03-27 04:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("traffic", "Traffic"),
                            ("construction", "Construction"),
                            ("obstruction", "Obstruction"),
                            ("weather", "Weather"),
                            ("accident", "Accident"),
                            ("emergency", "Emergency"),
                            ("natural_disaster", "Natural Disaster"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("unverified", "Unverified"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(db_index=True, max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("cause", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                ("estimated_duration", models.CharField(blank=True, max_length=255)),
                ("recommended_actions", models.JSONField(default=list)),
                ("related_alerts", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "source",
                    models.CharField(
                        choices=[("api", "API"), ("user", "User")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "source_api",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drivebc", "DriveBC"),
                            ("vancouver_opendata", "Vancouver Open Data"),
                            ("311", "311 Service Requests"),
                            ("translink", "TransLink"),
                            ("weathercan", "WeatherCAN"),
                        ],
                        help_text="Which upstream API this came from. Blank for user reports.",
                        max_length=32,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID from the upstream API, used for deduplication.",
                        max_length=255,
                    ),
                ),
                (
                    "reported_by",
                    models.CharField(
                        blank=True,
                        help_text="User identifier for citizen reports. Blank for API-sourced incidents.",
                        max_length=255,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True for API-sourced incidents. False by default for user reports.",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-expire time. Null means no expiry.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident_type", "status"],
                        name="core_incide_inciden_21c325_idx",
                    ),
                    models.Index(
                        fields=["source", "verified"],
                        name="core_incide_source_2a64b5_idx",
                    ),
                    models.Index(
                        fields=["lat", "lng"], name="core_incide_lat_ec5a2f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id__gt", "")),
                        fields=("source_api", "external_id"),
                        name="unique_external_incident",
                    )
                ],
            },
        ),
    ]
