# Generated by Django 6.0.3 on 2026-03-27 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for citizen reports. Null for API-sourced incidents.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "notify_via",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Push Notification"),
                            ("sms", "SMS"),
                        ],
                        default="push",
                        max_length=8,
                    ),
                ),
                (
                    "alert_lead_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="How many minutes before departure to send route alerts.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='e.g. "Morning Commute"', max_length=100
                    ),
                ),
                (
                    "origin_label",
                    models.CharField(help_text='e.g. "Home"', max_length=255),
                ),
                ("origin_lat", models.FloatField()),
                ("origin_lng", models.FloatField()),
                (
                    "destination_label",
                    models.CharField(help_text='e.g. "Office"', max_length=255),
                ),
                ("destination_lat", models.FloatField()),
                ("destination_lng", models.FloatField()),
                (
                    "departure_time",
                    models.TimeField(help_text="Daily departure time, e.g. 08:30"),
                ),
                (
                    "active_days",
                    models.JSONField(
                        default=list,
                        help_text='List of active days e.g. ["mon","tue","wed","thu","fri"]',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_routes",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Route",
                "verbose_name_plural": "Saved Routes",
                "ordering": ["departure_time"],
            },
        ),
        migrations.CreateModel(
            name="RouteAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("warning", "Warning"),
                            ("update", "Update"),
                            ("clear", "Clear"),
                        ],
                        default="warning",
                        max_length=8,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_alerts",
                        to="core.incident",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.savedroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Alert",
                "verbose_name_plural": "Route Alerts",
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("route", "incident", "alert_type"),
                        name="unique_route_incident_alert",
                    )
                ],
            },
        ),
    ]
