# Generated by Django 6.0.3 on 2026-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userprofile_home_location"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="outagegeocode",
            new_name="core_outage_failed_17e7b1_idx",
            old_name="outagegeocode_failed_geocoded_idx",
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("traffic", "Traffic"),
                    ("construction", "Construction"),
                    ("obstruction", "Obstruction"),
                    ("weather", "Weather"),
                    ("accident", "Accident"),
                    ("emergency", "Emergency"),
                    ("natural_disaster", "Natural Disaster"),
                    ("earthquake", "Earthquake"),
                    ("power_outage", "Power Outage"),
                    ("border_wait", "Border Wait"),
                    ("general", "General"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="source_api",
            field=models.CharField(
                blank=True,
                choices=[
                    ("drivebc", "DriveBC"),
                    ("vancouver_opendata", "Vancouver Open Data"),
                    ("311", "311 Service Requests"),
                    ("translink", "TransLink"),
                    ("weathercan", "WeatherCAN"),
                    ("bchydro", "BC Hydro"),
                    ("nasafirms", "NASA FIRMS"),
                    ("usgs", "USGS Earthquakes"),
                    ("cbp", "CBP Border Wait Times"),
                ],
                help_text="Which upstream API this came from. Blank for user reports.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="outagegeocode",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
