# Generated by Django 6.0.3 on 2026-03-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Open511EventsSnapshot',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('payload', models.JSONField(help_text='Full Open511 /events JSON object returned by DriveBC.')),
                ('fetch_params', models.JSONField(blank=True, default=dict, help_text='Query parameters sent to the upstream /events request.')),
                ('fetched_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Open511 events snapshot',
                'verbose_name_plural': 'Open511 events snapshots',
            },
        ),
    ]
